modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="fasterladderclimbing"
displayName="Faster Ladder Climbing"
version="${version}"
authors="JaSpr"
description='''
Climb Ladders Faster
'''

#forge
[[dependencies.fasterladderclimbing]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"

#minecraft
[[dependencies.fasterladderclimbing]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"